- name: Add an apt signing key for CRI-O
  apt_key:
    url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23:/1.23.1/xUbuntu_20.04/Release.key"
    state: present

- name: Add apt repository for stable version of CRI-O
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23:/1.23.1/xUbuntu_20.04/ /"
    state: present
    filename: cri-o

- name: Add apt repository for stable version of libcontainers
  apt_repository:
    repo: "deb [arch=amd64] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /"
    state: present
    filename: libcontainers

- name: Install Podman and its dependencies
  apt:
    pkg: 
    - buildah
    - cri-o
    - cri-o-runc
    - libseccomp2
    - podman
    state: present 
    update_cache: true

- name: Start CRIO service and reload daemon process
  shell: |
    # Create the .conf file to load the modules at bootup
    cat <<EOF | sudo tee /etc/modules-load.d/crio.conf
      overlay
      br_netfilter
    EOF

    modprobe overlay
    modprobe br_netfilter

    # Set up required sysctl params, these persist across reboots.
    cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    EOF

    sysctl --system
    systemctl daemon-reload
    systemctl enable crio --now
  args:
    executable: /usr/bin/bash
