- hosts: all
  become: yes
  tasks:
  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      pkg:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      state: present
      update_cache: yes
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  handlers:
  - name: docker status
    service: name=docker state=started
